#!/bin/bash
set -euo pipefail

# the talos image builder.
# NB this can be one of:
#   imager: build locally using the ghcr.io/siderolabs/imager container image.
#   image_factory: build remotely using the image factory service at https://factory.talos.dev.
# NB this is automatically set to imager when running on linux 6.1+; otherwise,
#    it is set to image_factory.
talos_image_builder="$(perl -e 'print ((`uname -r` =~ /^(\d+\.\d+)/ && $1 >= 6.1) ? "imager" : "image_factory")')"

# see https://github.com/siderolabs/talos/releases
# renovate: datasource=github-releases depName=siderolabs/talos
talos_version="1.12.1"

# see https://github.com/siderolabs/extensions/pkgs/container/qemu-guest-agent
# see https://github.com/siderolabs/extensions/tree/main/guest-agents/qemu-guest-agent
talos_qemu_guest_agent_extension_tag="10.2.0@sha256:b2843f69e3cd31ba813c1164f290ebbfddd239d53b3a0eeb19eb2f91fec6fed7"

# see https://github.com/siderolabs/extensions/pkgs/container/iscsi-tools
# see https://github.com/siderolabs/extensions/tree/main/storage/iscsi-tools
talos_iscsi_tools_extension_tag="v0.2.0@sha256:1011cc9acc7f30a78893185a75d107689a0d7735e7041a1d5e1c913135c32fc2"
                                               
# see https://github.com/siderolabs/extensions/pkgs/container/util-linux-tools
talos_util_linux_tools_extension_tag="v2.41.2@sha256:bcaf485539d7d07ee2988d1f189df74c54f8ad818017bcebe88207618e54b86c"

export CHECKPOINT_DISABLE='1'
export TF_LOG='DEBUG' # TRACE, DEBUG, INFO, WARN or ERROR.
export TF_LOG_PATH='terraform.log'

export TALOSCONFIG=$PWD/talosconfig.yml
export KUBECONFIG=$PWD/kubeconfig.yml

function step {
  echo "### $* ###"
}

function update-talos-extension {
  # see https://github.com/siderolabs/extensions?tab=readme-ov-file#installing-extensions
  local variable_name="$1"
  local image_name="$2"
  local images="$3"
  local image="$(grep -F "$image_name:" <<<"$images")"
  local tag="${image#*:}"
  echo "updating the talos extension to $image..."
  variable_name="$variable_name" tag="$tag" perl -i -pe '
    BEGIN {
      $var = $ENV{variable_name};
      $val = $ENV{tag};
    }
    s/^(\Q$var\E=).*/$1"$val"/;
  ' do
}

function update-talos-extensions {
  step "updating the talos extensions"
  local images="$(crane export "ghcr.io/siderolabs/extensions:v$talos_version" | tar x -O image-digests)"
  update-talos-extension talos_qemu_guest_agent_extension_tag ghcr.io/siderolabs/qemu-guest-agent "$images"
  update-talos-extension talos_iscsi_tools_extension_tag ghcr.io/siderolabs/iscsi-tools "$images"
  update-talos-extension talos_util_linux_tools_extension_tag ghcr.io/siderolabs/util-linux-tools "$images"
}

function build_talos_image__imager {
  # see https://docs.siderolabs.com/talos/v1.12/platform-specific-installations/boot-assets
  # see https://docs.siderolabs.com/talos/v1.12/platform-specific-installations/bare-metal-platforms/network-config
  # see Profile type at https://github.com/siderolabs/talos/blob/v1.12.1/pkg/imager/profile/profile.go#L24-L47
  local talos_version_tag="v$talos_version"
  rm -rf tmp/talos
  mkdir -p tmp/talos
  cat >"tmp/talos/talos-$talos_version.yml" <<EOF
arch: amd64
platform: nocloud
secureboot: false
version: $talos_version_tag
customization:
  extraKernelArgs:
    - net.ifnames=0
input:
  kernel:
    path: /usr/install/amd64/vmlinuz
  initramfs:
    path: /usr/install/amd64/initramfs.xz
  baseInstaller:
    imageRef: ghcr.io/siderolabs/installer:$talos_version_tag
  systemExtensions:
    - imageRef: ghcr.io/siderolabs/qemu-guest-agent:$talos_qemu_guest_agent_extension_tag
    - imageRef: ghcr.io/siderolabs/iscsi-tools:$talos_iscsi_tools_extension_tag
    - imageRef: ghcr.io/siderolabs/util-linux-tools:$talos_util_linux_tools_extension_tag
output:
  kind: image
  imageOptions:
    diskSize: $((2*1024*1024*1024))
    diskFormat: raw
  outFormat: raw
EOF
  echo "creating image..."
  docker run --rm -i \
    -v $PWD/tmp/talos:/secureboot:ro \
    -v $PWD/tmp/talos:/out \
    -v /dev:/dev \
    --privileged \
    "ghcr.io/siderolabs/imager:$talos_version_tag" \
    - < "tmp/talos/talos-$talos_version.yml"
}

function build_talos_image__image_factory {
  # see https://docs.siderolabs.com/talos/v1.12/learn-more/image-factory
  # see https://github.com/siderolabs/image-factory?tab=readme-ov-file#http-frontend-api
  local talos_version_tag="v$talos_version"
  rm -rf tmp/talos
  mkdir -p tmp/talos
  echo "creating image factory schematic..."
  cat >"tmp/talos/talos-$talos_version.yml" <<EOF
customization:
  extraKernelArgs:
    - net.ifnames=0
  systemExtensions:
    officialExtensions:
      - siderolabs/qemu-guest-agent
      - siderolabs/iscsi-tools
      - siderolabs/util-linux-tools
EOF
  local schematic_response="$(curl \
    -X POST \
    --silent \
    --data-binary @"tmp/talos/talos-$talos_version.yml" \
    https://factory.talos.dev/schematics)"
  local schematic_id="$(jq -r .id <<<"$schematic_response")"
  if [ -z "$schematic_id" ]; then
    echo "ERROR: Failed to create the image schematic."
    exit 1
  fi
  local image_url="https://factory.talos.dev/image/$schematic_id/$talos_version_tag/nocloud-amd64.raw.xz"
  echo "downloading image from $image_url..."
  rm -f tmp/talos/nocloud-amd64.raw.xz
  curl \
    --silent \
    -fsSL --output tmp/talos/nocloud-amd64.raw.xz \
    "$image_url"
  echo "extracting image..."
  xz -d tmp/talos/nocloud-amd64.raw.xz
}

function build_talos_image {
  case "$talos_image_builder" in
    imager)
      build_talos_image__imager
      ;;
    image_factory)
      build_talos_image__image_factory
      ;;
    *)
      echo $"unknown talos_image_builder $talos_image_builder"
      exit 1
      ;;
  esac
  echo "converting image to the qcow2 format..."
  local talos_libvirt_base_volume_name="talos-$talos_version.qcow2"
  qemu-img convert -O qcow2 tmp/talos/nocloud-amd64.raw tmp/talos/$talos_libvirt_base_volume_name
  qemu-img info tmp/talos/$talos_libvirt_base_volume_name
  if [ -n "$(virsh vol-list default | grep $talos_libvirt_base_volume_name)" ]; then
    virsh vol-delete --pool default $talos_libvirt_base_volume_name
  fi
  echo "uploading image to libvirt..."
  virsh vol-create-as default $talos_libvirt_base_volume_name 10M
  virsh vol-upload --pool default $talos_libvirt_base_volume_name tmp/talos/$talos_libvirt_base_volume_name
  cat >terraform.tfvars <<EOF
talos_version                  = "$talos_version"
talos_libvirt_base_volume_name = "$talos_libvirt_base_volume_name"
EOF
}

function init {
  step 'build talos image'
  build_talos_image
  step 'terraform init'
  terraform init -lockfile=readonly
}

function plan {
  step 'terraform plan'
  terraform plan -out=tfplan
}

function apply {
  step 'terraform apply'
  terraform apply tfplan
  terraform output -raw talosconfig >talosconfig.yml
  terraform output -raw kubeconfig >kubeconfig.yml
#  health
#  export-kubernetes-ingress-ca-crt
  info
  ovn
}

function health {
  step 'talosctl health'
  local controllers="$(terraform output -raw controllers)"
  local workers="$(terraform output -raw workers)"
  local c0="$(echo $controllers | cut -d , -f 1)"
  talosctl -e $c0 -n $c0 \
    health \
    --control-plane-nodes $controllers \
    --worker-nodes $workers
}

function ovn {
  step 'ovn'
  ###Install Kube OVN
  #https://docs.rackspacecloud.com/k8s-cni-kube-ovn/#prerequisites
  
  cat > /etc/genestack/helm-configs/kube-ovn/kube-ovn-helm-overrides.yaml <<EOF
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.
  ---
  global:
    registry:
      address: docker.io/kubeovn
      imagePullSecrets: []
  networking:
    IFACE: eth0
    vlan:
      VLAN_INTERFACE_NAME: eth0
  OPENVSWITCH_DIR: /var/lib/openvswitch
  OVN_DIR: /var/lib/ovn
  DISABLE_MODULES_MANAGEMENT: true
  EOF
  kubectl label node -l beta.kubernetes.io/os=linux kubernetes.io/os=linux
  kubectl label node -l node-role.kubernetes.io/control-plane kube-ovn/role=master
  kubectl label node -l ovn.kubernetes.io/ovs_dp_type!=userspace ovn.kubernetes.io/ovs_dp_type=kernel 
  sudo /opt/genestack/bin/install-kube-ovn.sh
}

function info {
  local controllers="$(terraform output -raw controllers)"
  local workers="$(terraform output -raw workers)"
  local nodes=($(echo "$controllers,$workers" | tr ',' ' '))
  step 'talos node os-release'
  for n in "${nodes[@]}"; do
    talosctl -n $n read /etc/os-release \
      | sed -E "s,(.+),$n: \1,g"
  done
  step 'kubernetes nodes'
  kubectl get nodes -o wide
}

function export-kubernetes-ingress-ca-crt {
  step 'export kubernetes-ingress-ca-crt.pem'
  kubectl get -n cert-manager secret/ingress-tls -o jsonpath='{.data.tls\.crt}' \
    | base64 -d \
    > kubernetes-ingress-ca-crt.pem
}

function upgrade {
  step 'talosctl upgrade'
  local controllers=($(terraform output -raw controllers | tr ',' ' '))
  local workers=($(terraform output -raw workers | tr ',' ' '))
  for n in "${controllers[@]}" "${workers[@]}"; do
    talosctl -e $n -n $n upgrade --preserve --wait
  done
  health
}

function destroy {
  terraform destroy -auto-approve
}

case $1 in
  update-talos-extensions)
    update-talos-extensions
    ;;
  init)
    init
    ;;
  plan)
    plan
    ;;
  apply)
    apply
    ;;
  plan-apply)
    plan
    apply
    ;;
  health)
    health
    ;;
  info)
    info
    ;;
  destroy)
    destroy
    ;;
  *)
    echo $"Usage: $0 {init|plan|apply|plan-apply|health|info}"
    exit 1
    ;;
esac
